# 一定特别注意学号要写正确！！！
# wid、DATETIME_CYCLE、DWMC_698799三项不用修改，其余根据自己情况修改一下

- wid: ''
  学号: ''
  DATETIME_CYCLE: ''
  DWMC_698799: ''
  学号_: ''
  姓名: ''
  常住地址: '' 
  常住地址_具体到门牌号: ''
  现居住地址: ''
  现居住地址_具体到门牌号: ''
  学生返校出发地: ''
  现居住地与返校地不同的原因: ''
  人员类型: '研究生'
  特殊情况类型: '无'
  昨日中午体温: '36.7'
  昨晚体温: '36.7'
  今晨体温: '36.7'
  近期乘坐交通工具: '无'
  联系电话: ''
  基本情况: '无'
  备注: ''
